import type { KitchenUnitSpec } from '@/types/furniture';

export const KITCHEN_UNIT_REGISTRY: Record<string, KitchenUnitSpec> = {
  'UK-B150': {
    code: 'UK-B150',
    name: 'Ultra-Slim Pullout Base 150mm',
    family: 'base',
    width: 150,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Full Height Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
  },
  'UK-B300': {
    code: 'UK-B300',
    name: 'Slim Single Base 300mm',
    family: 'base',
    width: 300,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Base Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
  },
  'UK-B400': {
    code: 'UK-B400',
    name: 'Standard Small Single 400mm',
    family: 'base',
    width: 400,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Base Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
  },
  'UK-B450': {
    code: 'UK-B450',
    name: 'Standard Medium Single 450mm',
    family: 'base',
    width: 450,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Base Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
  },
  'UK-B500': {
    code: 'UK-B500',
    name: 'Standard Single Base 500mm',
    family: 'base',
    width: 500,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Base Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
  },
  'UK-B600': {
    code: 'UK-B600',
    name: 'Standard Large Single 600mm',
    family: 'base',
    width: 600,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Base Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
  },
  'UK-B800': {
    code: 'UK-B800',
    name: 'Standard Double Base 800mm',
    family: 'base',
    width: 800,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Twin Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
  },
  'UK-B900': {
    code: 'UK-B900',
    name: 'Large Double Base 900mm',
    family: 'base',
    width: 900,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Twin Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
  },
  'UK-B1000': {
    code: 'UK-B1000',
    name: 'Extra Wide Double Base 1000mm',
    family: 'base',
    width: 1000,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Twin Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
  },
  'UK-B1200': {
    code: 'UK-B1200',
    name: 'Maximum Double Base 1200mm',
    family: 'base',
    width: 1200,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Twin Doors With Mullion', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
  },
  'UK-DL300': {
    code: 'UK-DL300',
    name: 'Drawer Line Single 300mm',
    family: 'drawer_line',
    width: 300,
    height: 720,
    depth: 560,
    frontLayout: [
      { kind: 'drawer_front', label: 'Top Drawer', height: 140, quantity: 1 },
      { kind: 'door', label: 'Bottom Door', height: 575, quantity: 1 },
    ],
    usesTopStretchers: true,
  },
  'UK-DL400': {
    code: 'UK-DL400',
    name: 'Drawer Line Single 400mm',
    family: 'drawer_line',
    width: 400,
    height: 720,
    depth: 560,
    frontLayout: [
      { kind: 'drawer_front', label: 'Top Drawer', height: 140, quantity: 1 },
      { kind: 'door', label: 'Bottom Door', height: 575, quantity: 1 },
    ],
    usesTopStretchers: true,
  },
  'UK-DL500': {
    code: 'UK-DL500',
    name: 'Drawer Line Single 500mm',
    family: 'drawer_line',
    width: 500,
    height: 720,
    depth: 560,
    frontLayout: [
      { kind: 'drawer_front', label: 'Top Drawer', height: 140, quantity: 1 },
      { kind: 'door', label: 'Bottom Door', height: 575, quantity: 1 },
    ],
    usesTopStretchers: true,
  },
  'UK-DL600': {
    code: 'UK-DL600',
    name: 'Drawer Line Single 600mm',
    family: 'drawer_line',
    width: 600,
    height: 720,
    depth: 560,
    frontLayout: [
      { kind: 'drawer_front', label: 'Top Drawer', height: 140, quantity: 1 },
      { kind: 'door', label: 'Bottom Door', height: 575, quantity: 1 },
    ],
    usesTopStretchers: true,
  },
  'UK-DR3-600': {
    code: 'UK-DR3-600',
    name: '3-Drawer Pan Unit 600mm',
    family: 'drawer_line',
    width: 600,
    height: 720,
    depth: 560,
    frontLayout: [
      { kind: 'drawer_front', label: 'Top Drawer', height: 140, quantity: 1 },
      { kind: 'drawer_front', label: 'Pan Drawer', height: 283, quantity: 2 },
    ],
    usesTopStretchers: true,
  },
  'UK-DR3-800': {
    code: 'UK-DR3-800',
    name: '3-Drawer Pan Unit 800mm',
    family: 'drawer_line',
    width: 800,
    height: 720,
    depth: 560,
    frontLayout: [
      { kind: 'drawer_front', label: 'Top Drawer', height: 140, quantity: 1 },
      { kind: 'drawer_front', label: 'Pan Drawer', height: 283, quantity: 2 },
    ],
    usesTopStretchers: true,
  },
  'UK-DR3-900': {
    code: 'UK-DR3-900',
    name: '3-Drawer Pan Unit 900mm',
    family: 'drawer_line',
    width: 900,
    height: 720,
    depth: 560,
    frontLayout: [
      { kind: 'drawer_front', label: 'Top Drawer', height: 140, quantity: 1 },
      { kind: 'drawer_front', label: 'Pan Drawer', height: 283, quantity: 2 },
    ],
    usesTopStretchers: true,
  },
  'UK-DR4-500': {
    code: 'UK-DR4-500',
    name: '4-Drawer Standard 500mm',
    family: 'drawer_line',
    width: 500,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'drawer_front', label: 'Equal Drawer', height: 176, quantity: 4 }],
    usesTopStretchers: true,
  },
  'UK-CBL900': {
    code: 'UK-CBL900',
    name: 'Blind Corner Base 900mm',
    family: 'corner_base',
    width: 900,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Corner Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
    notes: 'Represents the front-facing carcass portion of the blind corner unit.',
  },
  'UK-CBL1000': {
    code: 'UK-CBL1000',
    name: 'Blind Corner Base 1000mm',
    family: 'corner_base',
    width: 1000,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Corner Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
    notes: 'Represents the front-facing carcass portion of the blind corner unit.',
  },
  'UK-LCNR910': {
    code: 'UK-LCNR910',
    name: 'L-Shaped Corner Base 910mm',
    family: 'corner_base',
    width: 910,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Bi-Fold Corner Door', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
  },
  'UK-W300': {
    code: 'UK-W300',
    name: 'Wall Unit Small 300mm',
    family: 'wall',
    width: 300,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Wall Door', height: 720, quantity: 1 }],
    usesTopStretchers: false,
  },
  'UK-W400': {
    code: 'UK-W400',
    name: 'Wall Unit Med-Small 400mm',
    family: 'wall',
    width: 400,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Wall Door', height: 720, quantity: 1 }],
    usesTopStretchers: false,
  },
  'UK-W500': {
    code: 'UK-W500',
    name: 'Wall Unit Medium 500mm',
    family: 'wall',
    width: 500,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Wall Door', height: 720, quantity: 1 }],
    usesTopStretchers: false,
  },
  'UK-W600': {
    code: 'UK-W600',
    name: 'Wall Unit Large 600mm',
    family: 'wall',
    width: 600,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Wall Door', height: 720, quantity: 1 }],
    usesTopStretchers: false,
  },
  'UK-W800': {
    code: 'UK-W800',
    name: 'Wall Unit Double 800mm',
    family: 'wall',
    width: 800,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Twin Meeting Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: false,
  },
  'UK-W1000': {
    code: 'UK-W1000',
    name: 'Wall Unit X-Large 1000mm',
    family: 'wall',
    width: 1000,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Twin Meeting Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: false,
  },
  'UK-WC600': {
    code: 'UK-WC600',
    name: 'Wall Diagonal Corner 600mm',
    family: 'wall',
    width: 600,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Diagonal Door', height: 720, quantity: 1 }],
    usesTopStretchers: false,
  },
  'UK-T300': {
    code: 'UK-T300',
    name: 'Slim Pullout Larder 300mm',
    family: 'tall',
    width: 300,
    height: 1970,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Full Height Door', height: 1970, quantity: 1 }],
    usesTopStretchers: false,
  },
  'UK-T500': {
    code: 'UK-T500',
    name: 'Medium Larder Storage 500mm',
    family: 'tall',
    width: 500,
    height: 1970,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Split Larder Doors', height: 1970, quantity: 2, paired: true }],
    usesTopStretchers: false,
  },
  'UK-T600': {
    code: 'UK-T600',
    name: 'Large Larder Storage 600mm',
    family: 'tall',
    width: 600,
    height: 1970,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Split Larder Doors', height: 1970, quantity: 2, paired: true }],
    usesTopStretchers: false,
  },
  'UK-AO600': {
    code: 'UK-AO600',
    name: 'Single Oven Housing 600mm',
    family: 'tall',
    width: 600,
    height: 1970,
    depth: 560,
    frontLayout: [
      { kind: 'door', label: 'Bottom Door', height: 720, quantity: 1 },
      { kind: 'blank', label: 'Oven Aperture', height: 595, quantity: 1 },
      { kind: 'door', label: 'Top Door', height: 655, quantity: 1 },
    ],
    usesTopStretchers: false,
  },
  'UK-DO600': {
    code: 'UK-DO600',
    name: 'Double Oven Housing 600mm',
    family: 'tall',
    width: 600,
    height: 1970,
    depth: 560,
    frontLayout: [
      { kind: 'door', label: 'Bottom Door', height: 575, quantity: 1 },
      { kind: 'blank', label: 'Double Oven Aperture', height: 880, quantity: 1 },
      { kind: 'door', label: 'Top Door', height: 515, quantity: 1 },
    ],
    usesTopStretchers: false,
  },
  'UK-SB600': {
    code: 'UK-SB600',
    name: 'Sink Base 600mm (False Back)',
    family: 'base',
    width: 600,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Sink Base Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
    includeBackPanel: false,
    notes: 'Sink base uses open rear service zone (false back).',
  },
  'UK-SB800': {
    code: 'UK-SB800',
    name: 'Sink Base 800mm (False Back)',
    family: 'base',
    width: 800,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Twin Sink Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
    includeBackPanel: false,
    notes: 'Sink base uses open rear service zone (false back).',
  },
  'UK-SB1000': {
    code: 'UK-SB1000',
    name: 'Sink Base 1000mm (False Back)',
    family: 'base',
    width: 1000,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Twin Sink Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
    includeBackPanel: false,
    notes: 'Sink base uses open rear service zone (false back).',
  },
  'UK-HB600': {
    code: 'UK-HB600',
    name: 'Hob Base 600mm (Reduced Front Rail)',
    family: 'base',
    width: 600,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Hob Base Door', height: 720, quantity: 1 }],
    usesTopStretchers: true,
    frontStretcherDepth: 60,
    rearStretcherDepth: 90,
  },
  'UK-HB800': {
    code: 'UK-HB800',
    name: 'Hob Base 800mm (Reduced Front Rail)',
    family: 'base',
    width: 800,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Twin Hob Doors', height: 720, quantity: 2, paired: true }],
    usesTopStretchers: true,
    frontStretcherDepth: 60,
    rearStretcherDepth: 90,
  },
  'UK-IDW600': {
    code: 'UK-IDW600',
    name: 'Integrated Dishwasher Housing 600mm',
    family: 'appliance_base',
    width: 600,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Integrated Dishwasher Front', height: 715, quantity: 1 }],
    usesTopStretchers: true,
    includeBottomPanel: false,
    includeBackPanel: false,
    frontStretcherDepth: 60,
    rearStretcherDepth: 90,
    notes: 'Carcass rails only for integrated dishwasher void.',
  },
  'UK-IFF7030-600': {
    code: 'UK-IFF7030-600',
    name: 'Integrated Fridge Freezer Housing 70/30 600mm',
    family: 'tall',
    width: 600,
    height: 1970,
    depth: 560,
    frontLayout: [
      { kind: 'door', label: 'Lower Freezer Door', height: 725, quantity: 1 },
      { kind: 'door', label: 'Upper Fridge Door', height: 1240, quantity: 1 },
    ],
    usesTopStretchers: false,
    includeBackPanel: false,
    shelfCount: 0,
    notes: 'Integrated appliance housing with open rear for ventilation.',
  },
  'UK-IFULL-600': {
    code: 'UK-IFULL-600',
    name: 'Integrated Full Fridge Housing 600mm',
    family: 'tall',
    width: 600,
    height: 1970,
    depth: 560,
    frontLayout: [{ kind: 'door', label: 'Full Height Fridge Door', height: 1970, quantity: 1 }],
    usesTopStretchers: false,
    includeBackPanel: false,
    shelfCount: 0,
    notes: 'Integrated appliance housing with open rear for ventilation.',
  },
  'UK-BW600': {
    code: 'UK-BW600',
    name: 'Bridging Wall Unit 600mm',
    family: 'bridge_wall',
    width: 600,
    height: 360,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Bridge Door', height: 360, quantity: 1 }],
    usesTopStretchers: false,
    serviceVoid: 0,
    shelfCount: 0,
  },
  'UK-BW800': {
    code: 'UK-BW800',
    name: 'Bridging Wall Unit 800mm',
    family: 'bridge_wall',
    width: 800,
    height: 360,
    depth: 300,
    frontLayout: [{ kind: 'door', label: 'Twin Bridge Doors', height: 360, quantity: 2, paired: true }],
    usesTopStretchers: false,
    serviceVoid: 0,
    shelfCount: 0,
  },
  'UK-OW300': {
    code: 'UK-OW300',
    name: 'Open Wall Display 300mm',
    family: 'open_wall',
    width: 300,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'blank', label: 'Open Front', height: 720, quantity: 1 }],
    usesTopStretchers: false,
    serviceVoid: 0,
    shelfCount: 1,
  },
  'UK-OW600': {
    code: 'UK-OW600',
    name: 'Open Wall Display 600mm',
    family: 'open_wall',
    width: 600,
    height: 720,
    depth: 300,
    frontLayout: [{ kind: 'blank', label: 'Open Front', height: 720, quantity: 1 }],
    usesTopStretchers: false,
    serviceVoid: 0,
    shelfCount: 2,
  },
  'UK-OD600': {
    code: 'UK-OD600',
    name: 'Open Base Display Unit 600mm',
    family: 'base',
    width: 600,
    height: 720,
    depth: 560,
    frontLayout: [{ kind: 'blank', label: 'Open Front', height: 720, quantity: 1 }],
    usesTopStretchers: true,
    shelfCount: 1,
  },
};

export const DEFAULT_KITCHEN_UNIT_CODE = 'UK-B600';

export function getKitchenUnitSpec(code?: string): KitchenUnitSpec {
  return KITCHEN_UNIT_REGISTRY[code || DEFAULT_KITCHEN_UNIT_CODE] ?? KITCHEN_UNIT_REGISTRY[DEFAULT_KITCHEN_UNIT_CODE];
}