import Link from "next/link";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Service | Its My Cutlist",
  description: "Terms and conditions of using Its My Cutlist. Future-proofed compliance through Spring 2027.",
};

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-slate-950 text-slate-100 font-sans">
      {/* Mini header */}
      <header className="border-b border-slate-900 bg-slate-950/80 backdrop-blur sticky top-0 z-30 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 group">
            <span className="text-xl font-bold tracking-tight text-white group-hover:text-emerald-400 transition-colors">
              ITS MY <span className="text-emerald-400">CUTLIST</span>
            </span>
          </Link>
          <Link
            href="/"
            className="text-xs px-3.5 py-2 rounded-lg bg-slate-900 border border-slate-800 hover:bg-slate-800 text-slate-300 font-medium transition-all"
          >
            Back to Cockpit
          </Link>
        </div>
      </header>

      {/* Main content */}
      <main className="flex-1 max-w-4xl mx-auto px-6 py-12">
        <div className="space-y-8">
          <div>
            <div className="text-xs font-mono uppercase tracking-widest text-emerald-400 mb-2">
              Legal Infrastructure
            </div>
            <h1 className="text-4xl font-extrabold text-white tracking-tight">
              Terms of Service
            </h1>
            <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400 font-mono">
              <span>Status: Future-Proofed (Spring 2027)</span>
              <span>•</span>
              <span>Contact: hello@itsmyapp.co.uk</span>
            </div>
          </div>

          <div className="prose prose-invert max-w-none text-slate-300 space-y-6 leading-relaxed">
            <section className="bg-slate-900/50 p-6 rounded-xl border border-slate-900 space-y-3">
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>
                1. Acceptance of Terms
              </h2>
              <p className="text-sm">
                By accessing or using the "Its My Cutlist" application, you agree to be bound by these Terms of Service. If you do not agree, you must cease using the app immediately.
              </p>
            </section>

            <section className="bg-slate-900/50 p-6 rounded-xl border border-slate-900 space-y-3">
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>
                2. User Responsibilities
              </h2>
              <p className="text-sm">
                Users are solely responsible for their account security, including the security and confidentiality of any shared lockbox codes, keys, local settings, and export tokens generated by the application.
              </p>
            </section>

            <section className="bg-slate-900/50 p-6 rounded-xl border border-slate-900 space-y-3">
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>
                3. Prohibited Uses
              </h2>
              <p className="text-sm">
                You agree not to engage in unlawful use, transmitting malware or destructive scripts, circumventing the 5-device license validation gate, or impersonating personnel or customer services associated with the application.
              </p>
            </section>

            <section className="bg-slate-900/50 p-6 rounded-xl border border-slate-900 space-y-3">
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>
                4. Liability
              </h2>
              <p className="text-sm">
                Its My Cutlist is provided &quot;as is&quot;. We are not liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from material cuts executed using the layouts calculated by the app.
              </p>
            </section>

            <section className="bg-slate-900/50 p-6 rounded-xl border border-slate-900 space-y-3">
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>
                5. Termination
              </h2>
              <p className="text-sm">
                We reserve the right to suspend, terminate, or restrict your access to the application or revoke validation tokens at any time, without notice or liability, for breaches of these terms.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
